package graphemesToPhonemesConverters;

public class GraphemesToEnglishPhonemesConverter extends NaiveGraphemesToPhonemesConverter
{
	private final static String[][][] englishGraphemes = new String[][][]{
			{{"a"}, {"AA"}},
			{{"ą"}, {"AW"}},
			{{"b"}, {"B"}},
			{{"c"}, {"T S"}},
			{{"ci"}, {"CH IH"}},
			{{"cia"}, {"CH Y AA"}},
			{{"cią"}, {"CH Y AW"}},
			{{"cie"}, {"CH Y EH"}},
			{{"cię"}, {"CH Y ER W"}},
			{{"cio"}, {"CH Y AO"}},
			{{"ció"}, {"CH Y UH"}},
			{{"ciu"}, {"CH Y UH"}},
			{{"ć"}, {"CH"}},
			{{"cz"}, {"T CH"}},
			{{"d"}, {"D"}},
			{{"dz"}, {"JH"}},
			{{"dzia"}, {"JH Y AA"}},
			{{"dzią"}, {"JH Y AW"}},
			{{"dzie"}, {"JH Y EH"}},
			{{"dzię"}, {"JH Y ER W"}},
			{{"dzio"}, {"JH Y AO"}},
			{{"dzió"}, {"JH Y UH"}},
			{{"dziu"}, {"JH Y UH"}},
			{{"dż"}, {"JH"}},
			{{"dź"}, {"JH"}},
			{{"e"}, {"EH"}},
			{{"ę"}, {"ER W"}},
			{{"f"}, {"F"}},
			{{"g"}, {"G"}},
			{{"h"}, {"HH"}},
			{{"ch"}, {"HH"}},
			{{"chrz"}, {"HH SH"}},
			{{"i"}, {"IH"}},
			{{"ij"}, {"IY"}},
			{{"ia"}, {"Y AA"}},
			{{"ią"}, {"Y AW"}},
			{{"ie"}, {"Y EH"}},
			{{"ię"}, {"Y ER W"}},
			{{"io"}, {"Y AO"}},
			{{"ió"}, {"Y UH"}},
			{{"iu"}, {"Y UH"}},
			{{"j"}, {"Y"}},
			{{"k"}, {"K"}},
			{{"krz"}, {"K SH"}},
			{{"kż"}, {"K SH"}},
			{{"l"}, {"L"}},
			{{"ł"}, {"W"}},
			{{"m"}, {"M"}},
			{{"n"}, {"N"}},
			{{"ń"}, {"N Y"}},
			{{"o"}, {"AO"}},
			{{"ó"}, {"UH"}},
			{{"p"}, {"P"}},
			{{"prz"}, {"P SH"}},
			{{"pi"}, {"P Y"}},
			{{"r"}, {"R"}},
			{{"rz"}, {"ZH"}},
			{{"s"}, {"S"}},
			{{"sia"}, {"SH AA"}},
			{{"sią"}, {"SH AW"}},
			{{"sie"}, {"SH EH"}},
			{{"się"}, {"SH ER W"}},
			{{"sio"}, {"SH AO"}},
			{{"sió"}, {"SH UH"}},
			{{"siu"}, {"SH UH"}},
			{{"sz"}, {"SH"}},
			{{"ś"}, {"SH"}},
			{{"t"}, {"T"}},
			{{"trz"}, {"T SH"}},
			{{"tż"}, {"T SH"}},
			{{"u"}, {"UH"}},
			{{"v"}, {"F", "V"}},
			{{"w"}, {"V"}},
			{{"y"}, {"IH"}},
			{{"z"}, {"Z"}},
			{{"ż"}, {"ZH"}},
			{{"ź"}, {"ZH"}},
			{{"ü"}, {"UH"}},
			{{"części"}, {"T CH ER W SH CH Y IH"}}
	};
	
	public GraphemesToEnglishPhonemesConverter()
	{
		super(englishGraphemes);
	}
}
