package graphemesToPhonemesConverters;

public class GraphemesToRussianPhonemesConverter extends NaiveGraphemesToPhonemesConverter
{
	private final static String[][][] russianGraphemes = new String[][][]{
			{{"a"}, {"aa"}},
			{{"ą"}, {"oo l"}},
			{{"b"}, {"b"}},
			{{"c"}, {"c"}},
			{{"ci"}, {"ch ii"}},
			{{"cia"}, {"ch aa"}},
			{{"cią"}, {"ch oo l"}},
			{{"cie"}, {"ch e"}},
			{{"cię"}, {"ch e l"}},
			{{"cio"}, {"ch oo"}},
			{{"ció"}, {"ch u"}},
			{{"ciu"}, {"ch u"}},
			{{"ć"}, {"ch"}},
			{{"cz"}, {"t sh"}},
			{{"d"}, {"d"}},
			{{"di"}, {"dd ii"}},
			{{"dia"}, {"dd aa"}},
			{{"dią"}, {"dd oo l"}},
			{{"die"}, {"dd e"}},
			{{"dię"}, {"dd e l"}},
			{{"dio"}, {"dd oo"}},
			{{"dió"}, {"dd u"}},
			{{"diu"}, {"dd u"}},
			{{"dz"}, {"d z"}},
			{{"dzi"}, {"d zz ii"}},
			{{"dzia"}, {"d zz aa"}},
			{{"dzią"}, {"d zz oo l"}},
			{{"dzie"}, {"d zz e"}},
			{{"dzię"}, {"d zz e l"}},
			{{"dzio"}, {"d zz oo"}},
			{{"dzió"}, {"d zz u"}},
			{{"dziu"}, {"d zz u"}},
			{{"dż"}, {"d zh"}},
			{{"dź"}, {"d zh"}},
			{{"e"}, {"ee"}},
			{{"ę"}, {"ee l"}},
			{{"f"}, {"f"}},
			{{"fi"}, {"ff ii"}},
			{{"fia"}, {"ff aa"}},
			{{"fią"}, {"ff oo l"}},
			{{"fie"}, {"ff e"}},
			{{"fię"}, {"ff e l"}},
			{{"fio"}, {"ff oo"}},
			{{"fió"}, {"ff u"}},
			{{"fiu"}, {"ff u"}},
			{{"g"}, {"g"}},
			{{"gi"}, {"gg ii"}},
			{{"gia"}, {"gg aa"}},
			{{"gią"}, {"gg oo l"}},
			{{"gie"}, {"gg e"}},
			{{"gię"}, {"gg e l"}},
			{{"gio"}, {"gg oo"}},
			{{"gió"}, {"gg u"}},
			{{"giu"}, {"gg u"}},
			{{"h"}, {"h"}},
			{{"hi"}, {"hh ii"}},
			{{"hia"}, {"hh aa"}},
			{{"hią"}, {"hh oo l"}},
			{{"hie"}, {"hh e"}},
			{{"hię"}, {"hh e l"}},
			{{"hio"}, {"hh oo"}},
			{{"hió"}, {"hh u"}},
			{{"hiu"}, {"hh u"}},
			{{"ch"}, {"h"}},
			{{"chi"}, {"hh ii"}},
			{{"chia"}, {"hh aa"}},
			{{"chią"}, {"hh oo l"}},
			{{"chie"}, {"hh e"}},
			{{"chię"}, {"hh e l"}},
			{{"chio"}, {"hh oo"}},
			{{"chió"}, {"hh u"}},
			{{"chiu"}, {"hh u"}},
			{{"chrz"}, {"h sh"}},
			{{"chż"}, {"h sh"}},
			{{"i"}, {"i"}},
			{{"j"}, {"j"}},
			{{"k"}, {"k"}},
			{{"ki"}, {"kk ii"}},
			{{"kia"}, {"kk aa"}},
			{{"kią"}, {"kk oo l"}},
			{{"kie"}, {"kk e"}},
			{{"kię"}, {"kk e l"}},
			{{"kio"}, {"kk oo"}},
			{{"kió"}, {"kk u"}},
			{{"kiu"}, {"kk u"}},
			{{"krz"}, {"k sh"}},
			{{"kż"}, {"k sh"}},
			{{"l"}, {"ll"}},
			{{"ł"}, {"l"}},
			{{"m"}, {"m"}},
			{{"mi"}, {"mm ii"}},
			{{"mia"}, {"mm aa"}},
			{{"mią"}, {"mm oo l"}},
			{{"mie"}, {"mm e"}},
			{{"mię"}, {"mm e l"}},
			{{"mio"}, {"mm oo"}},
			{{"mió"}, {"mm u"}},
			{{"miu"}, {"mm u"}},
			{{"n"}, {"n"}},
			{{"ni"}, {"nn ii"}},
			{{"nia"}, {"nn aa"}},
			{{"nią"}, {"nn oo l"}},
			{{"nie"}, {"nn e"}},
			{{"nię"}, {"nn e l"}},
			{{"nio"}, {"nn oo"}},
			{{"nió"}, {"nn u"}},
			{{"niu"}, {"nn u"}},
			{{"ń"}, {"nn"}},
			{{"o"}, {"oo", "ay"}},
			{{"ó"}, {"uu"}},
			{{"p"}, {"p"}},
			{{"pi"}, {"pp ii"}},
			{{"pia"}, {"pp aa"}},
			{{"pią"}, {"pp oo l"}},
			{{"pie"}, {"pp e"}},
			{{"pię"}, {"pp e l"}},
			{{"pio"}, {"pp oo"}},
			{{"pió"}, {"pp u"}},
			{{"piu"}, {"pp u"}},
			{{"prz"}, {"p sh"}},
			{{"r"}, {"r"}},
			{{"ri"}, {"rr ii"}},
			{{"ria"}, {"rr aa"}},
			{{"rią"}, {"rr oo l"}},
			{{"rie"}, {"rr e"}},
			{{"rię"}, {"rr e l"}},
			{{"rio"}, {"rr oo"}},
			{{"rió"}, {"rr u"}},
			{{"riu"}, {"rr u"}},
			{{"rz"}, {"zh"}},
			{{"s"}, {"s"}},
			{{"sia"}, {"sh aa"}},
			{{"sią"}, {"sh oo l"}},
			{{"sie"}, {"sh e"}},
			{{"się"}, {"sh e l"}},
			{{"sio"}, {"sh oo"}},
			{{"sió"}, {"sh u"}},
			{{"siu"}, {"sh u"}},
			{{"sz"}, {"sh"}},
			{{"ś"}, {"sh"}},
			{{"t"}, {"t"}},
			{{"ti"}, {"tt ii"}},
			{{"tia"}, {"tt aa"}},
			{{"tią"}, {"tt oo l"}},
			{{"tie"}, {"tt e"}},
			{{"tię"}, {"tt e l"}},
			{{"tio"}, {"tt oo"}},
			{{"tió"}, {"tt u"}},
			{{"tiu"}, {"tt u"}},
			{{"trz"}, {"t sh"}},
			{{"tż"}, {"t sh"}},
			{{"u"}, {"u"}},
			{{"v"}, {"v", "f"}},
			{{"w"}, {"v", "f"}},
			{{"y"}, {"y"}},
			{{"z"}, {"z", "ss"}},
			{{"ż"}, {"zh"}},
			{{"ź"}, {"zh"}},
			{{"ü"}, {"u"}}
	};
	public GraphemesToRussianPhonemesConverter()
	{
		super(russianGraphemes);
	}

}
